### ISSUE TITLE
Halifax data missing?

### ISSUE THREAD

**Issue by daniel-simeone** [mountainMath/cmhc#14]
It seems that the Halifax data is now missing. Perhaps the underlying structure has been changed?

`cmhc::get_cmhc(survey = "Rms", series = "Vacancy Rate", dimension = "Bedroom Type", breakdown = "Historical Time Periods", geo_uid = 205, year = 2020)`
and
`cmhc::get_cmhc(survey = "Rms", series = "Vacancy Rate", dimension = "Bedroom Type", breakdown = "Survey Zones", geo_uid = 205)`

Both give "No data available."

The given survey/series/dimension/breakdown all appear in list_cmhc_tables() and the SGC Code (205) is as given by get_cmhc_geography(level = "MET")

This is the case for all calls to geo_uid 205 that I looked at (across all 31 tables that have both Historical Time Periods and Survey Zones as available breakdowns).

I'll try to look into the get_cmhc function to see what is happening.

**Comment by daniel-simeone** [comment]
The data is still available:
![image](https://user-images.githubusercontent.com/109553256/222468333-cd1e45be-f391-4511-b471-2e07bbb29a41.png)


Maybe the "API" changed?

**Comment by daniel-simeone** [comment]
The data is still on the website by survey zone:
![image](https://user-images.githubusercontent.com/109553256/222468668-c558fe06-c3eb-4f61-aca1-d246e11b488e.png)
Maybe the "API" changed somehow?

**Comment by mountainMath** [comment]
I noticed that too and did send in a note to CMHC a couple of days ago, no response yet. Will follow up. In the meantime, you can get the historical data from StatCan Table 34-10-0130.
`
get_cansim("34-10-0130") |>
  filter(GeoUID=="205")
`

**Comment by daniel-simeone** [comment]
Thank you!

**Comment by mountainMath** [comment]
I still have not heard anything official from CMHC, but it seems that they have renamed the internal identifier for Halifax CMA. It works if the new identifier is specified directly:
```
cmhc::get_cmhc(survey = "Rms", series = "Vacancy Rate", dimension = "Bedroom Type", breakdown = "Historical Time Periods", geo_uid ='1209034', year = 2020)
```
However, the package won't translate it automatically back to the StatCan geographic identifier.

**Comment by daniel-simeone** [comment]
Thanks for that. 
 Do you happen to have the Halifax-area zone IDs (the new ones) available easily in the same way you found that? Or you can tell how you figured that out, and I can do it?

I was looking through the (refreshed) GDB files, and they aren't there (nor is this new one for the city).

And it is still showing the 0580 in the URL and in the page code for Halifax zones, and in the queries I've looked with the Chrome inspector on the Housing Information Portal.

**Comment by mountainMath** [comment]
I think I got thing wrong in my explanation above, made some updates. Data for the CMA still seems to be missing, which is very unfortunate. The workaround above is getting data for the city not the CMA, which had identical boundaries in 2016.

**Comment by mountainMath** [comment]
This seems to be fixed now, at least in the current development branch
